### ISSUE TITLE
当popup_position为center时，不能正确分页

### ISSUE THREAD

**Issue by VimWei** [skywind3000/vim-navigator#12]
若窗口比较大，一页可以容纳所有内容，这是正常情形：

![image](https://github.com/skywind3000/vim-navigator/assets/25874852/d8cf3f4b-cb0a-467f-9eb8-6a202fb3dbb0)

若窗口比较小，一页难以容纳所有内容时，本应该分页，但实际情形是不可见：

![image](https://github.com/skywind3000/vim-navigator/assets/25874852/5809ddf4-f53c-4f77-88d6-addcdf2d70ce)

**Comment by skywind3000** [comment]
thanks, 最新版已经修正。

**Comment by VimWei** [comment]
Cool！问题解决了，感谢！
